### ISSUE TITLE
Github Metadata Plugin - Personal Access Token

### ISSUE THREAD

**Issue by selimerunkut** [longpdo/neumorphism#20]
Hello

after adding the 

> Personal Access Token
to the env file and saving it to the project root, as described in the readme

got this message from github

> We noticed that a valid OAuth, GitHub App or Personal Access Token of yours was committed to a GitHub repository. Disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.
As a precautionary measure, we have revoked the token. You will need to generate a new token for the app to authenticate to GitHub.

how can I solve this issue?

**Comment by longpdo** [comment]
Thanks for checking out this repository. Been kinda behind on checking up on my own open source repositories.

Reading the mentioned issue, It seems like you already found another solution to your problem.

But regarding the original problem - for other readers in the future with a similar problem,
it seems odd that you got the message from Github. Like I described - one shall create the `.env` file in the project root locally. And that file should never be pushed to Github - since the `.gitignore` file includes `.env`. An environment file or similar secret files should never be pushed to Github.
