### ISSUE TITLE
Adding new landing page icons

### ISSUE THREAD

**Issue by drewnutt** [longpdo/neumorphism#30]
How can I add a new icon for a different site on the landing page? 

All of the images are in brands.svg, but I am unable to look at that file and see what they look like. I would like to integrate a [Google Scholar button](https://commons.wikimedia.org/wiki/File:Google_Scholar_logo.svg) but I am unable to just reference this svg directly. It does not seem to understand where it is supposed to fill in the color.

**Comment by longpdo** [comment]
Hi drewnutt,

fyi the brands.svg comes from Fontawesome - Previews of included svgs can be seen here: https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=brands

Since Fontawesome does not include a Google Scholar icon - a workaround would be:

* you provide the icon yourself and save the .svg file inside /assets/img/ e.g. /assets/img/google_scholar.svg
* in landing-page.html - copy one of the html snippets for one icon and change it accordingly to point to the Google Scholar icon

e.g. i copied the Twitter code and changed some of the values.
* one thing, which still needs some work is in the first line the href value - change `https://scholar.google.de/youruserid` with the url of your actual profile page you want to link to

```
<a class="social-link twitter" aria-label="My Google Scholar" target="_blank" rel="noreferrer" href="https://scholar.google.de/youruserid">
  <svg viewBox="0 0 200 200" class="circle">
    <circle cx="100" cy="100" r="80" />
  </svg>
  <div class="social">
    <svg class="social-svg" viewBox="0 0 48 48">
      <use x="12" y="12" width="24" height="24" viewBox="0 0 48 48" xlink:href="{{ "/assets/img/google_scholar.svg" | prepend: site.baseurl }}"></use>
    </svg>
  </div>
  <span class="label">Google Scholar</span>
</a>
```

**Comment by drewnutt** [comment]
I finally figured out my issue. The svg needs to have a path within a symbol group in its xml and needs to have a viewBox for itself.
