### ISSUE TITLE
No CSS working when setting on github page

### ISSUE THREAD

**Issue by Npizza** [longpdo/neumorphism#6]
I am trying to set up the theme on github pages and the css it seems broken. Can anyone help me please?

![image](https://user-images.githubusercontent.com/25034947/85949579-48f16500-b960-11ea-928a-c649d54ae231.png)

**Comment by longpdo** [comment]
Thanks for your checking out my theme.

If you want to use this and deploy to Github Pages, you should setup your own repository first - you can follow the steps described [here](https://github.com/longpdo/neumorphism#installation).

Else can you tell me, what you have done so far?

**Comment by Npizza** [comment]
I found what the problem was.
it was a path problem. Check this commit https://github.com/Npizza/test-site/commit/68ec68ed074d18033bc6afc8b981f07790d482e6 

I would like to if it is possible to add a newsletter to the theme! Do you think that it is possible?
(Thanks for your theme it is really impressive!)

**Comment by longpdo** [comment]
Yeah it is a path problem. In your case, I would revert that commit and add your `test-site/` baseurl into the [config file line 10](https://github.com/Npizza/test-site/blob/master/_config.yml)

Explanation:
The href links you changed are always checking the config file for a baseurl to prepend with `| prepend: site.baseurl`.
In the description, I added that you should only leave the baseurl empty, if your repository is named `npizza.github.io`. Since you named it `test-site`, you would need to add that to baseurl.

**Comment by Npizza** [comment]
I am looking to connect it with mailchimp and have some subscribers that I can send them mails

**Comment by longpdo** [comment]
I see. 
I just checked it out and it would be possible.

For starters go to https://mailchimp.com/en/help/add-a-signup-form-to-your-website/ and generate the HTML code for your embedded form.

To integrate that into your page, I would add that generated HTML code to the `section-contact.html` file. Then I would change the css styling, e.g. change the input field to match the `project tags` and the subscribe button to be similar as the buttons in the `timeline section`.
